export const SUBMIT_MESSAGE_START = "SUBMIT_MESSAGE_START";
export const SUBMIT_MESSAGE_SUCCESS = "SUBMIT_MESSAGE_SUCCESS";
export const SUBMIT_MESSAGE_FAIL = "SUBMIT_MESSAGE_FAIL";
export const SUBMIT_MESSAGE_RESET = "SUBMIT_MESSAGE_RESET";

export const FETCH_MESSAGES_START = "FETCH_MESSAGES_START";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAIL = "FETCH_MESSAGES_FAIL";
export const RESET_MESSAGES = "RESET_MESSAGES";

export const FETCH_MESSAGE_START = "FETCH_MESSAGE_START";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_FAIL = "FETCH_MESSAGE_FAIL";
export const RESET_MESSAGE = "RESET_MESSAGE";

export const EDIT_MESSAGE_START = "EDIT_MESSAGE_START";
export const EDIT_MESSAGE_SUCCESS = "EDIT_MESSAGE_SUCCESS";
export const EDIT_MESSAGE_FAIL = "EDIT_MESSAGE_FAIL";
export const EDIT_MESSAGE_RESET = "EDIT_MESSAGE_RESET";

export const APPROVE_MESSAGE_START = "APPROVE_MESSAGE_START";
export const APPROVE_MESSAGE_SUCCESS = "APPROVE_MESSAGE_SUCCESS";
export const APPROVE_MESSAGE_FAIL = "APPROVE_MESSAGE_FAIL";
export const APPROVE_MESSAGE_RESET = "APPROVE_MESSAGE_RESET";

export const DELETE_MESSAGE_START = "DELETE_MESSAGE_START";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL";
export const DELETE_MESSAGE_RESET = "DELETE_MESSAGE_RESET";

export const ADD_FILTER = "ADD_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";

export const FILTER_MESSAGES_START = "FILTER_MESSAGES_START";
export const FILTER_MESSAGES_ADD = "FILTER_MESSAGES_ADD";
export const FILTER_MESSAGES_REMOVE = "FILTER_MESSAGES_REMOVE";
export const FILTER_MESSAGES_FAIL = "FILTER_MESSAGES_FAIL";
export const FILTER_MESSAGES = "FILTER_MESSAGES";

export const SORT_APPROVED_START = "SORT_APPROVED_START";
export const SORT_APPROVED_ADD = "SORT_APPROVED_ADD";
export const SORT_APPROVED_REMOVE = "SORT_APPROVED_REMOVE";
export const SORT_APPROVED_FAIL = "SORT_APPROVED_FAIL";
export const SORT_APPROVED = "SORT_APPPROVED";

export const SORT_PENDING_START = "SORT_PENDING_START";
export const SORT_PENDING_ADD = "SORT_PENDING_ADD";
export const SORT_PENDING_REMOVE = "SORT_PENDING_REMOVE";
export const SORT_PENDING_FAIL = "SORT_PENDING_FAIL";
export const SORT_PENDING = "SORT_PENDING";

export const SORT_RESET = "SORT_RESET";
export const FILTER_RESET = "FILTER_RESET";

export const SORT_USERS_REGISTERED_START = "SORT_USERS_REGISTERED_START";
export const SORT_USERS_REGISTERED_ADD = "SORT_USERS_REGISTERED_ADD";
export const SORT_USERS_REGISTERED_REMOVE = "SORT_USERS_REGISTERED_REMOVE";
export const SORT_USERS_REGISTERED_FAIL = "SORT_USERS_REGISTERED_FAIL";
export const SORT_USERS_REGISTERED = "SORT_USERS_REGISTERED";

export const SORT_USERS_PENDING_START = "SORT_USERS_PENDING_START";
export const SORT_USERS_PENDING_ADD = "SORT_USERS_PENDING_ADD";
export const SORT_USERS_PENDING_REMOVE = "SORT_USERS_PENDING_REMOVE";
export const SORT_USERS_PENDING_FAIL = "SORT_USERS_PENDING_FAIL";
export const SORT_USERS_PENDING = "SORT_USERS_PENDING";

export const SORT_USERS_RESET = "SORT_USERS_RESET";

export const GET_PERSONS_START = "GET_PERSONS_START";
export const GET_PERSONS_SUCCESS = "GET_PERSONS_SUCCESS";
export const GET_PERSONS_FAIL = "GET_PERSONS_FAIL";
export const GET_PERSONS_RESET = "GET_PERSONS_RESET";

export const GET_PERSON_START = "GET_PERSON_START";
export const GET_PERSON_SUCCESS = "GET_PERSON_SUCCESS";
export const GET_PERSON_FAIL = "GET_PERSON_FAIL";
export const GET_PERSON_RESET = "GET_PERSON_RESET";

export const ADD_PERSON_START = "ADD_PERSON_START";
export const ADD_PERSON_SUCCESS = "ADD_PERSON_SUCCESS";
export const ADD_PERSON_FAIL = "ADD_PERSON_FAIL";
export const ADD_PERSON_RESET = "ADD_PERSON_RESET";

export const EDIT_PERSON_START = "EDIT_PERSON_START";
export const EDIT_PERSON_SUCCESS = "EDIT_PERSON_SUCCESS";
export const EDIT_PERSON_FAIL = "EDIT_PERSON_FAIL";
export const EDIT_PERSON_RESET = "EDIT_PERSON_RESET";

export const ORDER_PERSON_START = "ORDER_PERSON_START";
export const ORDER_PERSON_SUCCESS = "ORDER_PERSON_SUCCESS";
export const ORDER_PERSON_FAIL = "ORDER_PERSON_FAIL";

export const DELETE_PERSON_START = "DELETE_PERSON_START";
export const DELETE_PERSON_SUCCESS = "DELETE_PERSON_SUCCESS";
export const DELETE_PERSON_FAIL = "DELETE_PERSON_FAIL";
export const DELETE_PERSON_RESET = "DELETE_PERSON_RESET";

export const GET_RESOURCES_START = "GET_RESOURCES_START";
export const GET_RESOURCES_SUCCESS = "GET_RESOURCES_SUCCESS";
export const GET_RESOURCES_FAIL = "GET_RESOURCES_FAIL";
export const GET_RESOURCES_RESET = "GET_RESOURCES_RESET";

export const GET_RESOURCE_START = "GET_RESOURCE_START";
export const GET_RESOURCE_SUCCESS = "GET_RESOURCE_SUCCESS";
export const GET_RESOURCE_FAIL = "GET_RESOURCE_FAIL";
export const GET_RESOURCE_RESET = "GET_RESOURCE_RESET";

export const ADD_RESOURCE_START = "ADD_RESOURCE_START";
export const ADD_RESOURCE_SUCCESS = "ADD_RESOURCE_SUCCESS";
export const ADD_RESOURCE_FAIL = "ADD_RESOURCE_FAIL";
export const ADD_RESOURCE_RESET = "ADD_RESOURCE_RESET";

export const EDIT_RESOURCE_START = "EDIT_RESOURCE_START";
export const EDIT_RESOURCE_SUCCESS = "EDIT_RESOURCE_SUCCESS";
export const EDIT_RESOURCE_FAIL = "EDIT_RESOURCE_FAIL";
export const EDIT_RESOURCE_RESET = "EDIT_RESOURCE_RESET";

export const DELETE_RESOURCE_START = "DELETE_RESOURCE_START";
export const DELETE_RESOURCE_SUCCESS = "DELETE_RESOURCE_SUCCESS";
export const DELETE_RESOURCE_FAIL = "DELETE_RESOURCE_FAIL";
export const DELETE_RESOURCE_RESET = "DELETE_RESOURCE_RESET";

export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_USERS_RESET = "GET_USERS_RESET";

export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_RESET = "GET_USER_RESET";

export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_USER_RESET = "ADD_USER_RESET";

export const EDIT_USER_START = "EDIT_USER_START";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";
export const EDIT_USER_RESET = "EDIT_USER_RESET";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const CHECK_AUTH_START = "CHECK_AUTH_START";
export const CHECK_AUTH_SUCCESS = "CHECK_AUTH_SUCCESS";
export const CHECK_AUTH_FAIL = "CHECK_AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const TOGGLE_NOTIFICATION_START = "TOGGLE_NOTIFICATION_START";
export const TOGGLE_NOTIFICATION_SUCCESS = "TOGGLE_NOTIFICATION_SUCCESS";
export const TOGGLE_NOTIFICATION_FAIL = "TOGGLE_NOTIFICATION_FAIL";
export const TOGGLE_NOTIFICATION_RESET = "TOGGLE_NOTIFICATION_RESET";
